export const NAV_DRAWER_OPEN = 'NAV_DRAWER_OPEN';
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';

export const CLEAR_CURRENT_PROFILE='CLEAR_CURRENT_PROFILE'